using Croptor.Domain.Common.ValueObjects;
using Croptor.Domain.Presets;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Croptor.Infrastructure.Persistence.Configurations
{
    public class PresetsConfigurations : IEntityTypeConfiguration<Preset>
    {
        public void Configure(EntityTypeBuilder<Preset> builder)
        {
            // AddDefaultData(builder);

            builder.OwnsMany(preset => preset.Sizes);

            builder.HasIndex(preset => new { preset.UserId, preset.Name });
        }

        // private static void AddDefaultData(EntityTypeBuilder<Preset> builder)
        // {
        //     builder.HasData(
        //         Preset.Create("Instagram", null, new List<Size>
        //             {
        //                 new Size(1080, 1920, "Story",
        //                     new Uri("https://localhost:7091/api/images/get/icons/instagram.svg")),
        //                 new Size(1080, 566, "Landscape Carousel",
        //                     new Uri("https://localhost:7091/api/images/get/icons/instagram.svg")),
        //                 new Size(1080, 1350, "Portrait Carousel",
        //                     new Uri("https://localhost:7091/api/images/get/icons/instagram.svg")),
        //                 new Size(1080, 1080, "Square Carousel",
        //                     new Uri("https://localhost:7091/api/images/get/icons/instagram.svg")),
        //                 new Size(1080, 566, "Landscape Ad",
        //                     new Uri("https://localhost:7091/api/images/get/icons/instagram.svg")),
        //                 new Size(1080, 1080, "Square Ad",
        //                     new Uri("https://localhost:7091/api/images/get/icons/instagram.svg")),
        //                 new Size(61, 61, "Thumbnail",
        //                     new Uri("https://localhost:7091/api/images/get/icons/instagram.svg")),
        //             },
        //             new Uri("https://localhost:7091/api/images/get/icons/instagram.svg")),
        //         Preset.Create("Facebook", null, new List<Size>
        //             {
        //                 new Size(170, 170, "Profile Photo",
        //                     new Uri("https://localhost:7091/api/images/get/icons/facebook.svg")),
        //                 new Size(1200, 630, "Landscape",
        //                     new Uri("https://localhost:7091/api/images/get/icons/facebook.svg")),
        //                 new Size(630, 1200, "Portrait",
        //                     new Uri("https://localhost:7091/api/images/get/icons/facebook.svg")),
        //                 new Size(1200, 1200, "Square",
        //                     new Uri("https://localhost:7091/api/images/get/icons/facebook.svg")),
        //                 new Size(1080, 1920, "Stories",
        //                     new Uri("https://localhost:7091/api/images/get/icons/facebook.svg")),
        //                 new Size(851, 315, "Cover Photo",
        //                     new Uri("https://localhost:7091/api/images/get/icons/facebook.svg")),
        //                 new Size(1080, 1080, "Feed Ads",
        //                     new Uri("https://localhost:7091/api/images/get/icons/facebook.svg")),
        //                 new Size(1080, 1080, "Instant Article",
        //                     new Uri("https://localhost:7091/api/images/get/icons/facebook.svg")),
        //                 new Size(1080, 1080, "Right Column Ads",
        //                     new Uri("https://localhost:7091/api/images/get/icons/facebook.svg")),
        //                 new Size(1080, 1080, "Marketplace Ads",
        //                     new Uri("https://localhost:7091/api/images/get/icons/facebook.svg")),
        //                 new Size(1080, 1080, "Facebook Search",
        //                     new Uri("https://localhost:7091/api/images/get/icons/facebook.svg")),
        //                 new Size(1080, 1080, "Sponsored Messages",
        //                     new Uri("https://localhost:7091/api/images/get/icons/facebook.svg")),
        //                 new Size(1080, 1080, "Messenger Inbox Ads",
        //                     new Uri("https://localhost:7091/api/images/get/icons/facebook.svg")),
        //                 new Size(1080, 1080, "Messenger Stories Ads",
        //                     new Uri("https://localhost:7091/api/images/get/icons/facebook.svg")),
        //                 new Size(1200, 628, "Event Cover Photo",
        //                     new Uri("https://localhost:7091/api/images/get/icons/facebook.svg")),
        //             },
        //             new Uri("https://localhost:7091/api/images/get/icons/facebook.svg")),
        //         Preset.Create("LinkedIn", null, new List<Size>
        //             {
        //                 new Size(1080, 1080, "Blog Post Link Image",
        //                     new Uri("https://localhost:7091/api/images/get/icons/linkedin.svg")),
        //                 new Size(1080, 1080, "Custom Image Sharing",
        //                     new Uri("https://localhost:7091/api/images/get/icons/linkedin.svg")),
        //                 new Size(300, 300, "Company Logo",
        //                     new Uri("https://localhost:7091/api/images/get/icons/linkedin.svg")),
        //                 new Size(60, 60, "Square Logo",
        //                     new Uri("https://localhost:7091/api/images/get/icons/linkedin.svg")),
        //                 new Size(1128, 191, "Page Cover Image",
        //                     new Uri("https://localhost:7091/api/images/get/icons/linkedin.svg")),
        //                 new Size(1128, 1376, "Life Tab Main Image",
        //                     new Uri("https://localhost:7091/api/images/get/icons/linkedin.svg")),
        //                 new Size(502, 282, "Life Tab Custom Modules",
        //                     new Uri("https://localhost:7091/api/images/get/icons/linkedin.svg")),
        //                 new Size(900, 600, "Life Tab Company Photo",
        //                     new Uri("https://localhost:7091/api/images/get/icons/linkedin.svg")),
        //                 new Size(300, 300, "Company Logo for Ads",
        //                     new Uri("https://localhost:7091/api/images/get/icons/linkedin.svg")),
        //                 new Size(60, 60, "Spotlights Ads Logo",
        //                     new Uri("https://localhost:7091/api/images/get/icons/linkedin.svg")),
        //                 new Size(1128, 376, "Sponsored Content",
        //                     new Uri("https://localhost:7091/api/images/get/icons/linkedin.svg")),
        //                 new Size(502, 282, "Sponsored Carousel",
        //                     new Uri("https://localhost:7091/api/images/get/icons/linkedin.svg")),
        //             },
        //             new Uri("https://localhost:7091/api/images/get/icons/linkedin.svg")),
        //         Preset.Create("Pinterest", null, new List<Size>
        //             {
        //                 new Size(1000, 1500, "Pin",
        //                     new Uri("https://localhost:7091/api/images/get/icons/pinterest.svg")),
        //                 new Size(1080, 1920, "Idea Pin",
        //                     new Uri("https://localhost:7091/api/images/get/icons/pinterest.svg")),
        //                 new Size(1000, 1000, "Square Pin",
        //                     new Uri("https://localhost:7091/api/images/get/icons/pinterest.svg")),
        //                 new Size(1000, 2100, "Long Pin",
        //                     new Uri("https://localhost:7091/api/images/get/icons/pinterest.svg")),
        //                 new Size(280, 280, "Profile Photo",
        //                     new Uri("https://localhost:7091/api/images/get/icons/pinterest.svg")),
        //                 new Size(600, 600, "Board Cover",
        //                     new Uri("https://localhost:7091/api/images/get/icons/pinterest.svg")),
        //                 new Size(1000, 1500, "Carousel Pin",
        //                     new Uri("https://localhost:7091/api/images/get/icons/pinterest.svg")),
        //                 new Size(1000, 1000, "Square Carousel Pin",
        //                     new Uri("https://localhost:7091/api/images/get/icons/pinterest.svg")),
        //                 new Size(1000, 1500, "Ad",
        //                     new Uri("https://localhost:7091/api/images/get/icons/pinterest.svg")),
        //                 new Size(1000, 1500, "Shopping Ads",
        //                     new Uri("https://localhost:7091/api/images/get/icons/pinterest.svg")),
        //                 new Size(1000, 1500, "App Install Ads",
        //                     new Uri("https://localhost:7091/api/images/get/icons/pinterest.svg")),
        //             },
        //             new Uri("https://localhost:7091/api/images/get/icons/pinterest.svg")),
        //         Preset.Create("Twitter", null, new List<Size>
        //             {
        //                 new Size(1600, 600, "Landscape Feed",
        //                     new Uri("https://localhost:7091/api/images/get/icons/twitter.svg")),
        //                 new Size(1200, 1200, "Square Feed",
        //                     new Uri("https://localhost:7091/api/images/get/icons/twitter.svg")),
        //                 new Size(1080, 1350, "Portrait Feed",
        //                     new Uri("https://localhost:7091/api/images/get/icons/twitter.svg")),
        //                 new Size(400, 400, "Profile",
        //                     new Uri("https://localhost:7091/api/images/get/icons/twitter.svg")),
        //                 new Size(1500, 500, "Header",
        //                     new Uri("https://localhost:7091/api/images/get/icons/twitter.svg")),
        //                 new Size(4096, 4096, "Twitter Card",
        //                     new Uri("https://localhost:7091/api/images/get/icons/twitter.svg")),
        //                 new Size(800, 418, "Website Card Ad",
        //                     new Uri("https://localhost:7091/api/images/get/icons/twitter.svg")),
        //                 new Size(800, 800, "App Card Image Ad",
        //                     new Uri("https://localhost:7091/api/images/get/icons/twitter.svg")),
        //                 new Size(800, 800, "Carousel Ad",
        //                     new Uri("https://localhost:7091/api/images/get/icons/twitter.svg")),
        //                 new Size(800, 418, "Direct Message Ad",
        //                     new Uri("https://localhost:7091/api/images/get/icons/twitter.svg")),
        //                 new Size(800, 418, "Conversation Card Ad",
        //                     new Uri("https://localhost:7091/api/images/get/icons/twitter.svg")),
        //             },
        //             new Uri("https://localhost:7091/api/images/get/icons/twitter.svg")),
        //         Preset.Create("Snapchat", null, new List<Size>
        //             {
        //                 new Size(1080, 1920, "Geofilter Image",
        //                     new Uri("https://localhost:7091/api/images/get/icons/snapchat.svg")),
        //                 new Size(1080, 1920, "Image Ad",
        //                     new Uri("https://localhost:7091/api/images/get/icons/snapchat.svg")),
        //             },
        //             new Uri("https://localhost:7091/api/images/get/icons/snapchat.svg")),
        //         Preset.Create("Twitch", null, new List<Size>
        //             {
        //                 new Size(1200, 480, "Profile Banner",
        //                     new Uri("https://localhost:7091/api/images/get/icons/twitch.svg")),
        //                 new Size(1920, 480, "Offline Banner",
        //                     new Uri("https://localhost:7091/api/images/get/icons/twitch.svg")),
        //                 new Size(256, 256, "Avatar", new Uri("https://localhost:7091/api/images/get/icons/twitch.svg")),
        //                 new Size(320, 100, "Panels", new Uri("https://localhost:7091/api/images/get/icons/twitch.svg")),
        //                 new Size(1280, 720, "Thumbnail",
        //                     new Uri("https://localhost:7091/api/images/get/icons/twitch.svg")),
        //                 new Size(1920, 1080, "Overlay",
        //                     new Uri("https://localhost:7091/api/images/get/icons/twitch.svg")),
        //                 new Size(112, 112, "Emotes", new Uri("https://localhost:7091/api/images/get/icons/twitch.svg")),
        //                 new Size(72, 72, "Badges", new Uri("https://localhost:7091/api/images/get/icons/twitch.svg")),
        //             },
        //             new Uri("https://localhost:7091/api/images/get/icons/twitch.svg")),
        //         Preset.Create("TikTok", null, new List<Size>
        //             {
        //                 new Size(200, 200, "Profile Photo",
        //                     new Uri("https://localhost:7091/api/images/get/icons/tiktok.svg")),
        //             },
        //             new Uri("https://localhost:7091/api/images/get/icons/tiktok.svg")),
        //         Preset.Create("YouTube", null, new List<Size>
        //             {
        //                 new Size(2048, 1152, "Banner",
        //                     new Uri("https://localhost:7091/api/images/get/icons/youtube.svg")),
        //                 new Size(1280, 720, "Video",
        //                     new Uri("https://localhost:7091/api/images/get/icons/youtube.svg")),
        //                 new Size(800, 800, "Channel Icon",
        //                     new Uri("https://localhost:7091/api/images/get/icons/youtube.svg")),
        //                 new Size(1280, 720, "Thumbnail",
        //                     new Uri("https://localhost:7091/api/images/get/icons/youtube.svg")),
        //             },
        //             new Uri("https://localhost:7091/api/images/get/icons/youtube.svg")),
        //         Preset.Create("Google Ads", null, new List<Size>
        //             {
        //                 new Size(600, 1067, "Vertical Display Network",
        //                     new Uri("https://localhost:7091/api/images/get/icons/google ads.svg")),
        //                 new Size(1628, 1200, "Landscape Display Network",
        //                     new Uri("https://localhost:7091/api/images/get/icons/google ads.svg")),
        //                 new Size(1200, 1200, "Square Display Network",
        //                     new Uri("https://localhost:7091/api/images/get/icons/google ads.svg")),
        //                 new Size(250, 250, "Square",
        //                     new Uri("https://localhost:7091/api/images/get/icons/google ads.svg")),
        //                 new Size(200, 200, "Small Square",
        //                     new Uri("https://localhost:7091/api/images/get/icons/google ads.svg")),
        //                 new Size(468, 60, "Banner",
        //                     new Uri("https://localhost:7091/api/images/get/icons/google ads.svg")),
        //                 new Size(728, 98, "Leaderboard",
        //                     new Uri("https://localhost:7091/api/images/get/icons/google ads.svg")),
        //                 new Size(300, 250, "Inline Rectangle",
        //                     new Uri("https://localhost:7091/api/images/get/icons/google ads.svg")),
        //                 new Size(336, 280, "Large Rectangle",
        //                     new Uri("https://localhost:7091/api/images/get/icons/google ads.svg")),
        //                 new Size(120, 600, "Skyscraper",
        //                     new Uri("https://localhost:7091/api/images/get/icons/google ads.svg")),
        //                 new Size(160, 600, "Wide Skyscraper",
        //                     new Uri("https://localhost:7091/api/images/get/icons/google ads.svg")),
        //                 new Size(300, 600, "Half Page ad",
        //                     new Uri("https://localhost:7091/api/images/get/icons/google ads.svg")),
        //                 new Size(970, 90, "Large Leaderboard",
        //                     new Uri("https://localhost:7091/api/images/get/icons/google ads.svg")),
        //                 new Size(300, 250, "Medium Rectangle",
        //                     new Uri("https://localhost:7091/api/images/get/icons/google ads.svg")),
        //                 new Size(300, 50, "Mobile banner",
        //                     new Uri("https://localhost:7091/api/images/get/icons/google ads.svg")),
        //                 new Size(320, 50, "Mobile banner",
        //                     new Uri("https://localhost:7091/api/images/get/icons/google ads.svg")),
        //                 new Size(320, 100, "Mobile large banner",
        //                     new Uri("https://localhost:7091/api/images/get/icons/google ads.svg")),
        //             },
        //             new Uri("https://localhost:7091/api/images/get/icons/google ads.svg")),
        //         Preset.Create("Reddit", null, new List<Size>
        //             {
        //                 new Size(1920, 128, "Small Ad Banner",
        //                     new Uri("https://localhost:7091/api/images/get/icons/reddit.svg")),
        //                 new Size(1920, 256, "Medium Ad Banner",
        //                     new Uri("https://localhost:7091/api/images/get/icons/reddit.svg")),
        //                 new Size(1920, 384, "Large Ad",
        //                     new Uri("https://localhost:7091/api/images/get/icons/reddit.svg")),
        //             },
        //             new Uri("https://localhost:7091/api/images/get/icons/reddit.svg")),
        //         Preset.Create("Art & Illustration", null, new List<Size>
        //             {
        //                 new Size(498, 708, "B5",
        //                     new Uri("https://localhost:7091/api/images/get/icons/custom-size.svg")),
        //                 new Size(728, 1031, "B4",
        //                     new Uri("https://localhost:7091/api/images/get/icons/custom-size.svg")),
        //                 new Size(1748, 2480, "A5",
        //                     new Uri("https://localhost:7091/api/images/get/icons/custom-size.svg")),
        //                 new Size(2480, 3508, "A4",
        //                     new Uri("https://localhost:7091/api/images/get/icons/custom-size.svg")),
        //                 new Size(3605, 4961, "A3",
        //                     new Uri("https://localhost:7091/api/images/get/icons/custom-size.svg")),
        //                 new Size(4961, 7016, "A2",
        //                     new Uri("https://localhost:7091/api/images/get/icons/custom-size.svg")),
        //             },
        //             new Uri("https://localhost:7091/api/images/get/icons/custom-size.svg"))
        //     );
        // }
    }
}